# Copyright (C) 2014-2016 The CyanogenMod Project
# Copyright (C) 2017-2021 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/sony/blue-common/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/sony/blue-common

PRODUCT_COPY_FILES += \
    vendor/sony/blue-common/proprietary/bin/ta_param_loader:$(TARGET_COPY_OUT_SYSTEM)/bin/ta_param_loader \
    vendor/sony/blue-common/proprietary/bin/ta_qmi_service:$(TARGET_COPY_OUT_SYSTEM)/bin/ta_qmi_service \
    vendor/sony/blue-common/proprietary/etc/firmware/q6.b00:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/q6.b00 \
    vendor/sony/blue-common/proprietary/etc/firmware/q6.b01:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/q6.b01 \
    vendor/sony/blue-common/proprietary/etc/firmware/q6.b03:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/q6.b03 \
    vendor/sony/blue-common/proprietary/etc/firmware/q6.b04:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/q6.b04 \
    vendor/sony/blue-common/proprietary/etc/firmware/q6.b05:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/q6.b05 \
    vendor/sony/blue-common/proprietary/etc/firmware/q6.b06:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/q6.b06 \
    vendor/sony/blue-common/proprietary/etc/firmware/q6.mdt:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/q6.mdt \
    vendor/sony/blue-common/proprietary/lib/hw/camera.vendor.qcom.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/camera.vendor.qcom.so \
    vendor/sony/blue-common/proprietary/lib/libcamera_clientsemc.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcamera_clientsemc.so \
    vendor/sony/blue-common/proprietary/lib/libcameralight.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcameralight.so \
    vendor/sony/blue-common/proprietary/lib/libface.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libface.so \
    vendor/sony/blue-common/proprietary/lib/liblights-core.so:$(TARGET_COPY_OUT_SYSTEM)/lib/liblights-core.so \
    vendor/sony/blue-common/proprietary/lib/libmiscta.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmiscta.so \
    vendor/sony/blue-common/proprietary/lib/libmllite.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmllite.so \
    vendor/sony/blue-common/proprietary/lib/libmlplatform.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmlplatform.so \
    vendor/sony/blue-common/proprietary/lib/libmmcamera_3a_legacy.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmmcamera_3a_legacy.so \
    vendor/sony/blue-common/proprietary/lib/libmmcamera_faceproc.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmmcamera_faceproc.so \
    vendor/sony/blue-common/proprietary/lib/libmmcamera_frameproc.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmmcamera_frameproc.so \
    vendor/sony/blue-common/proprietary/lib/libmmcamera_plugin.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmmcamera_plugin.so \
    vendor/sony/blue-common/proprietary/lib/libmmcamera_statsproc31.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmmcamera_statsproc31.so \
    vendor/sony/blue-common/proprietary/lib/libmpl.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmpl.so \
    vendor/sony/blue-common/proprietary/lib/libsys-utils.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsys-utils.so

PRODUCT_PACKAGES += \
    libMPU3050 \
    libsensors_akm8972 \
    libta

PRODUCT_COPY_FILES += \
    vendor/sony/blue-common/proprietary/bin/fm_qsoc_patches:$(TARGET_COPY_OUT_SYSTEM)/bin/fm_qsoc_patches \
    vendor/sony/blue-common/proprietary/bin/hci_qcomm_init:$(TARGET_COPY_OUT_SYSTEM)/bin/hci_qcomm_init \
    vendor/sony/blue-common/proprietary/bin/irsc_util:$(TARGET_COPY_OUT_SYSTEM)/bin/irsc_util \
    vendor/sony/blue-common/proprietary/bin/netmgrd:$(TARGET_COPY_OUT_SYSTEM)/bin/netmgrd \
    vendor/sony/blue-common/proprietary/bin/qmuxd:$(TARGET_COPY_OUT_SYSTEM)/bin/qmuxd \
    vendor/sony/blue-common/proprietary/bin/rmt_storage:$(TARGET_COPY_OUT_SYSTEM)/bin/rmt_storage \
    vendor/sony/blue-common/proprietary/bin/secchand:$(TARGET_COPY_OUT_SYSTEM)/bin/secchand \
    vendor/sony/blue-common/proprietary/etc/firmware/a225_pfp.fw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/a225_pfp.fw \
    vendor/sony/blue-common/proprietary/etc/firmware/a225_pm4.fw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/a225_pm4.fw \
    vendor/sony/blue-common/proprietary/etc/firmware/a225p5_pm4.fw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/a225p5_pm4.fw \
    vendor/sony/blue-common/proprietary/etc/firmware/a300_pfp.fw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/a300_pfp.fw \
    vendor/sony/blue-common/proprietary/etc/firmware/a300_pm4.fw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/a300_pm4.fw \
    vendor/sony/blue-common/proprietary/etc/firmware/leia_pfp_470.fw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/leia_pfp_470.fw \
    vendor/sony/blue-common/proprietary/etc/firmware/leia_pm4_470.fw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/leia_pm4_470.fw \
    vendor/sony/blue-common/proprietary/etc/firmware/vidc.b00:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/vidc.b00 \
    vendor/sony/blue-common/proprietary/etc/firmware/vidc.b01:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/vidc.b01 \
    vendor/sony/blue-common/proprietary/etc/firmware/vidc.b02:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/vidc.b02 \
    vendor/sony/blue-common/proprietary/etc/firmware/vidc.b03:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/vidc.b03 \
    vendor/sony/blue-common/proprietary/etc/firmware/vidc.mdt:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/vidc.mdt \
    vendor/sony/blue-common/proprietary/etc/firmware/vidc_1080p.fw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/vidc_1080p.fw \
    vendor/sony/blue-common/proprietary/etc/firmware/vidcfw.elf:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/vidcfw.elf \
    vendor/sony/blue-common/proprietary/etc/firmware/wcnss.b00:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/wcnss.b00 \
    vendor/sony/blue-common/proprietary/etc/firmware/wcnss.b01:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/wcnss.b01 \
    vendor/sony/blue-common/proprietary/etc/firmware/wcnss.b02:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/wcnss.b02 \
    vendor/sony/blue-common/proprietary/etc/firmware/wcnss.b04:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/wcnss.b04 \
    vendor/sony/blue-common/proprietary/etc/firmware/wcnss.b05:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/wcnss.b05 \
    vendor/sony/blue-common/proprietary/etc/firmware/wcnss.mdt:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/wcnss.mdt \
    vendor/sony/blue-common/proprietary/lib/hw/gps.default.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/gps.default.so \
    vendor/sony/blue-common/proprietary/lib/libQSEEComAPI.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libQSEEComAPI.so \
    vendor/sony/blue-common/proprietary/lib/lib_asb_tee.so:$(TARGET_COPY_OUT_SYSTEM)/lib/lib_asb_tee.so \
    vendor/sony/blue-common/proprietary/lib/libacdbloader.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libacdbloader.so \
    vendor/sony/blue-common/proprietary/lib/libadsprpc.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libadsprpc.so \
    vendor/sony/blue-common/proprietary/lib/libdsi_netctrl.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libdsi_netctrl.so \
    vendor/sony/blue-common/proprietary/lib/libdsutils.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libdsutils.so \
    vendor/sony/blue-common/proprietary/lib/libgemini.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libgemini.so \
    vendor/sony/blue-common/proprietary/lib/libgps.utils.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libgps.utils.so \
    vendor/sony/blue-common/proprietary/lib/libidd.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libidd.so \
    vendor/sony/blue-common/proprietary/lib/libidl.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libidl.so \
    vendor/sony/blue-common/proprietary/lib/libkeyctrl.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libkeyctrl.so \
    vendor/sony/blue-common/proprietary/lib/libloc_api_v02.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libloc_api_v02.so \
    vendor/sony/blue-common/proprietary/lib/libloc_core.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libloc_core.so \
    vendor/sony/blue-common/proprietary/lib/libloc_ds_api.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libloc_ds_api.so \
    vendor/sony/blue-common/proprietary/lib/libloc_eng.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libloc_eng.so \
    vendor/sony/blue-common/proprietary/lib/libmercury.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmercury.so \
    vendor/sony/blue-common/proprietary/lib/libmmcamera_hdr_lib.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmmcamera_hdr_lib.so \
    vendor/sony/blue-common/proprietary/lib/libmmcamera_image_stab.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmmcamera_image_stab.so \
    vendor/sony/blue-common/proprietary/lib/libmmcamera_tintless_algo.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmmcamera_tintless_algo.so \
    vendor/sony/blue-common/proprietary/lib/libmmcamera_tintless_wrapper.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmmcamera_tintless_wrapper.so \
    vendor/sony/blue-common/proprietary/lib/libmmcamera_wavelet_lib.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmmcamera_wavelet_lib.so \
    vendor/sony/blue-common/proprietary/lib/libmmjpeg.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmmjpeg.so \
    vendor/sony/blue-common/proprietary/lib/libnetmgr.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libnetmgr.so \
    vendor/sony/blue-common/proprietary/lib/libpin-cache.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libpin-cache.so \
    vendor/sony/blue-common/proprietary/lib/libprotobuf-c.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libprotobuf-c.so \
    vendor/sony/blue-common/proprietary/lib/libqcci_legacy.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libqcci_legacy.so \
    vendor/sony/blue-common/proprietary/lib/libqdi.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libqdi.so \
    vendor/sony/blue-common/proprietary/lib/libqdp.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libqdp.so \
    vendor/sony/blue-common/proprietary/lib/libqmi.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libqmi.so \
    vendor/sony/blue-common/proprietary/lib/libqmi_client_qmux.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libqmi_client_qmux.so \
    vendor/sony/blue-common/proprietary/lib/libqmiservices.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libqmiservices.so \
    vendor/sony/blue-common/proprietary/lib/libril-qc-qmi-1.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libril-qc-qmi-1.so \
    vendor/sony/blue-common/proprietary/lib/libs1sl.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libs1sl.so \
    vendor/sony/blue-common/proprietary/lib/libthermalclient.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libthermalclient.so \
    vendor/sony/blue-common/proprietary/vendor/lib/egl/eglsubAndroid.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/eglsubAndroid.so \
    vendor/sony/blue-common/proprietary/vendor/lib/egl/libEGL_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libEGL_adreno.so \
    vendor/sony/blue-common/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLESv1_CM_adreno.so \
    vendor/sony/blue-common/proprietary/vendor/lib/egl/libGLESv2S3D_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLESv2S3D_adreno.so \
    vendor/sony/blue-common/proprietary/vendor/lib/egl/libGLESv2_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLESv2_adreno.so \
    vendor/sony/blue-common/proprietary/vendor/lib/egl/libq3dtools_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libq3dtools_adreno.so \
    vendor/sony/blue-common/proprietary/vendor/lib/libC2D2.so:$(TARGET_COPY_OUT_VENDOR)/lib/libC2D2.so \
    vendor/sony/blue-common/proprietary/vendor/lib/libCB.so:$(TARGET_COPY_OUT_VENDOR)/lib/libCB.so \
    vendor/sony/blue-common/proprietary/vendor/lib/libOpenCL.so:$(TARGET_COPY_OUT_VENDOR)/lib/libOpenCL.so \
    vendor/sony/blue-common/proprietary/vendor/lib/libOpenVG.so:$(TARGET_COPY_OUT_VENDOR)/lib/libOpenVG.so \
    vendor/sony/blue-common/proprietary/vendor/lib/libadreno_utils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libadreno_utils.so \
    vendor/sony/blue-common/proprietary/vendor/lib/libc2d2_a3xx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libc2d2_a3xx.so \
    vendor/sony/blue-common/proprietary/vendor/lib/libc2d2_z180.so:$(TARGET_COPY_OUT_VENDOR)/lib/libc2d2_z180.so \
    vendor/sony/blue-common/proprietary/vendor/lib/libdiag.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdiag.so \
    vendor/sony/blue-common/proprietary/vendor/lib/libgeofence.so:$(TARGET_COPY_OUT_VENDOR)/lib/libgeofence.so \
    vendor/sony/blue-common/proprietary/vendor/lib/libgsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libgsl.so \
    vendor/sony/blue-common/proprietary/vendor/lib/libizat_core.so:$(TARGET_COPY_OUT_VENDOR)/lib/libizat_core.so \
    vendor/sony/blue-common/proprietary/vendor/lib/liblbs_core.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblbs_core.so \
    vendor/sony/blue-common/proprietary/vendor/lib/libllvm-a3xx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libllvm-a3xx.so \
    vendor/sony/blue-common/proprietary/vendor/lib/libllvm-arm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libllvm-arm.so \
    vendor/sony/blue-common/proprietary/vendor/lib/libqmi_cci.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_cci.so \
    vendor/sony/blue-common/proprietary/vendor/lib/libqmi_common_so.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_common_so.so \
    vendor/sony/blue-common/proprietary/vendor/lib/libqmi_csi.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_csi.so \
    vendor/sony/blue-common/proprietary/vendor/lib/libqmi_encdec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_encdec.so \
    vendor/sony/blue-common/proprietary/vendor/lib/libqti-perfd-client.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqti-perfd-client.so \
    vendor/sony/blue-common/proprietary/vendor/lib/libsc-a2xx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsc-a2xx.so \
    vendor/sony/blue-common/proprietary/vendor/lib/libsc-a3xx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsc-a3xx.so \
    vendor/sony/blue-common/proprietary/vendor/lib/libstlport.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstlport.so \
    vendor/sony/blue-common/proprietary/vendor/lib/libuiblur.so:$(TARGET_COPY_OUT_VENDOR)/lib/libuiblur.so \
    vendor/sony/blue-common/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:$(TARGET_COPY_OUT_VENDOR)/lib/mediadrm/libwvdrmengine.so

PRODUCT_PACKAGES += \
    libtime_genoff
