# Copyright (C) 2014-2016 The CyanogenMod Project
# Copyright (C) 2017-2021 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/sony/mint/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/sony/mint

PRODUCT_COPY_FILES += \
    vendor/sony/mint/proprietary/bin/rmi4_fwloader:$(TARGET_COPY_OUT_SYSTEM)/bin/rmi4_fwloader \
    vendor/sony/mint/proprietary/bin/updatemiscta:$(TARGET_COPY_OUT_SYSTEM)/bin/updatemiscta \
    vendor/sony/mint/proprietary/etc/firmware/dsps.b00:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/dsps.b00 \
    vendor/sony/mint/proprietary/etc/firmware/dsps.b01:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/dsps.b01 \
    vendor/sony/mint/proprietary/etc/firmware/dsps.b02:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/dsps.b02 \
    vendor/sony/mint/proprietary/etc/firmware/dsps.b03:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/dsps.b03 \
    vendor/sony/mint/proprietary/etc/firmware/dsps.b04:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/dsps.b04 \
    vendor/sony/mint/proprietary/etc/firmware/dsps.b05:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/dsps.b05 \
    vendor/sony/mint/proprietary/etc/firmware/dsps.mdt:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/dsps.mdt \
    vendor/sony/mint/proprietary/etc/firmware/dxhdcp2.b00:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/dxhdcp2.b00 \
    vendor/sony/mint/proprietary/etc/firmware/dxhdcp2.b01:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/dxhdcp2.b01 \
    vendor/sony/mint/proprietary/etc/firmware/dxhdcp2.b02:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/dxhdcp2.b02 \
    vendor/sony/mint/proprietary/etc/firmware/dxhdcp2.b03:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/dxhdcp2.b03 \
    vendor/sony/mint/proprietary/etc/firmware/dxhdcp2.mdt:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/dxhdcp2.mdt \
    vendor/sony/mint/proprietary/etc/firmware/touch_module_id_0x32.img:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/touch_module_id_0x32.img \
    vendor/sony/mint/proprietary/etc/firmware/tzlibasb.b00:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/tzlibasb.b00 \
    vendor/sony/mint/proprietary/etc/firmware/tzlibasb.b01:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/tzlibasb.b01 \
    vendor/sony/mint/proprietary/etc/firmware/tzlibasb.b02:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/tzlibasb.b02 \
    vendor/sony/mint/proprietary/etc/firmware/tzlibasb.b03:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/tzlibasb.b03 \
    vendor/sony/mint/proprietary/etc/firmware/tzlibasb.mdt:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/tzlibasb.mdt \
    vendor/sony/mint/proprietary/etc/firmware/tzs1sl.b00:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/tzs1sl.b00 \
    vendor/sony/mint/proprietary/etc/firmware/tzs1sl.b01:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/tzs1sl.b01 \
    vendor/sony/mint/proprietary/etc/firmware/tzs1sl.b02:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/tzs1sl.b02 \
    vendor/sony/mint/proprietary/etc/firmware/tzs1sl.b03:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/tzs1sl.b03 \
    vendor/sony/mint/proprietary/etc/firmware/tzs1sl.mdt:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/tzs1sl.mdt \
    vendor/sony/mint/proprietary/etc/firmware/tzsuntory.b00:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/tzsuntory.b00 \
    vendor/sony/mint/proprietary/etc/firmware/tzsuntory.b01:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/tzsuntory.b01 \
    vendor/sony/mint/proprietary/etc/firmware/tzsuntory.b02:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/tzsuntory.b02 \
    vendor/sony/mint/proprietary/etc/firmware/tzsuntory.b03:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/tzsuntory.b03 \
    vendor/sony/mint/proprietary/etc/firmware/tzsuntory.mdt:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/tzsuntory.mdt \
    vendor/sony/mint/proprietary/etc/flashled_calc_parameters.cfg:$(TARGET_COPY_OUT_SYSTEM)/etc/flashled_calc_parameters.cfg \
    vendor/sony/mint/proprietary/lib/hw/nfc.msm8960.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/nfc.msm8960.so \
    vendor/sony/mint/proprietary/lib/libals.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libals.so \
    vendor/sony/mint/proprietary/lib/libaudcal.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaudcal.so \
    vendor/sony/mint/proprietary/lib/libcald_client.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcald_client.so \
    vendor/sony/mint/proprietary/lib/libcald_hal.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcald_hal.so \
    vendor/sony/mint/proprietary/lib/libcald_imageutil.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcald_imageutil.so \
    vendor/sony/mint/proprietary/lib/libcald_pal.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcald_pal.so \
    vendor/sony/mint/proprietary/lib/libcald_server.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcald_server.so \
    vendor/sony/mint/proprietary/lib/libcald_util.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcald_util.so \
    vendor/sony/mint/proprietary/lib/liboemcamera.so:$(TARGET_COPY_OUT_SYSTEM)/lib/liboemcamera.so \
    vendor/sony/mint/proprietary/vendor/camera/APT01BM0.dat:$(TARGET_COPY_OUT_VENDOR)/camera/APT01BM0.dat \
    vendor/sony/mint/proprietary/vendor/camera/KMO13BS0.dat:$(TARGET_COPY_OUT_VENDOR)/camera/KMO13BS0.dat \
    vendor/sony/mint/proprietary/vendor/camera/KMO13BS0_BU6456.dat:$(TARGET_COPY_OUT_VENDOR)/camera/KMO13BS0_BU6456.dat \
    vendor/sony/mint/proprietary/vendor/camera/KMO13BS0_IMX091.dat:$(TARGET_COPY_OUT_VENDOR)/camera/KMO13BS0_IMX091.dat \
    vendor/sony/mint/proprietary/vendor/camera/SOI13BS0.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI13BS0.dat \
    vendor/sony/mint/proprietary/vendor/camera/SOI13BS0_BU6456.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI13BS0_BU6456.dat \
    vendor/sony/mint/proprietary/vendor/camera/SOI13BS0_IMX091.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI13BS0_IMX091.dat \
    vendor/sony/mint/proprietary/vendor/camera/STW01BM0.dat:$(TARGET_COPY_OUT_VENDOR)/camera/STW01BM0.dat \
    vendor/sony/mint/proprietary/vendor/camera/flash.dat:$(TARGET_COPY_OUT_VENDOR)/camera/flash.dat \
    vendor/sony/mint/proprietary/vendor/camera/product.dat:$(TARGET_COPY_OUT_VENDOR)/camera/product.dat

PRODUCT_COPY_FILES += \
    vendor/sony/mint/proprietary/etc/firmware/modem.b00:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem.b00 \
    vendor/sony/mint/proprietary/etc/firmware/modem.b01:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem.b01 \
    vendor/sony/mint/proprietary/etc/firmware/modem.b02:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem.b02 \
    vendor/sony/mint/proprietary/etc/firmware/modem.b03:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem.b03 \
    vendor/sony/mint/proprietary/etc/firmware/modem.b04:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem.b04 \
    vendor/sony/mint/proprietary/etc/firmware/modem.b06:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem.b06 \
    vendor/sony/mint/proprietary/etc/firmware/modem.b07:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem.b07 \
    vendor/sony/mint/proprietary/etc/firmware/modem.mdt:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem.mdt \
    vendor/sony/mint/proprietary/etc/firmware/modem_f1.b00:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_f1.b00 \
    vendor/sony/mint/proprietary/etc/firmware/modem_f1.b01:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_f1.b01 \
    vendor/sony/mint/proprietary/etc/firmware/modem_f1.b02:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_f1.b02 \
    vendor/sony/mint/proprietary/etc/firmware/modem_f1.b03:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_f1.b03 \
    vendor/sony/mint/proprietary/etc/firmware/modem_f1.b04:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_f1.b04 \
    vendor/sony/mint/proprietary/etc/firmware/modem_f1.b05:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_f1.b05 \
    vendor/sony/mint/proprietary/etc/firmware/modem_f1.b06:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_f1.b06 \
    vendor/sony/mint/proprietary/etc/firmware/modem_f1.b07:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_f1.b07 \
    vendor/sony/mint/proprietary/etc/firmware/modem_f1.b08:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_f1.b08 \
    vendor/sony/mint/proprietary/etc/firmware/modem_f1.b09:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_f1.b09 \
    vendor/sony/mint/proprietary/etc/firmware/modem_f1.b10:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_f1.b10 \
    vendor/sony/mint/proprietary/etc/firmware/modem_f1.b13:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_f1.b13 \
    vendor/sony/mint/proprietary/etc/firmware/modem_f1.b14:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_f1.b14 \
    vendor/sony/mint/proprietary/etc/firmware/modem_f1.b21:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_f1.b21 \
    vendor/sony/mint/proprietary/etc/firmware/modem_f1.b22:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_f1.b22 \
    vendor/sony/mint/proprietary/etc/firmware/modem_f1.b23:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_f1.b23 \
    vendor/sony/mint/proprietary/etc/firmware/modem_f1.b25:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_f1.b25 \
    vendor/sony/mint/proprietary/etc/firmware/modem_f1.b26:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_f1.b26 \
    vendor/sony/mint/proprietary/etc/firmware/modem_f1.b29:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_f1.b29 \
    vendor/sony/mint/proprietary/etc/firmware/modem_f1.mdt:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_f1.mdt \
    vendor/sony/mint/proprietary/etc/firmware/modem_fw.b00:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_fw.b00 \
    vendor/sony/mint/proprietary/etc/firmware/modem_fw.b01:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_fw.b01 \
    vendor/sony/mint/proprietary/etc/firmware/modem_fw.b02:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_fw.b02 \
    vendor/sony/mint/proprietary/etc/firmware/modem_fw.b03:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_fw.b03 \
    vendor/sony/mint/proprietary/etc/firmware/modem_fw.b04:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_fw.b04 \
    vendor/sony/mint/proprietary/etc/firmware/modem_fw.b05:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_fw.b05 \
    vendor/sony/mint/proprietary/etc/firmware/modem_fw.b06:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_fw.b06 \
    vendor/sony/mint/proprietary/etc/firmware/modem_fw.b07:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_fw.b07 \
    vendor/sony/mint/proprietary/etc/firmware/modem_fw.b08:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_fw.b08 \
    vendor/sony/mint/proprietary/etc/firmware/modem_fw.b09:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_fw.b09 \
    vendor/sony/mint/proprietary/etc/firmware/modem_fw.b10:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_fw.b10 \
    vendor/sony/mint/proprietary/etc/firmware/modem_fw.b13:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_fw.b13 \
    vendor/sony/mint/proprietary/etc/firmware/modem_fw.b14:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_fw.b14 \
    vendor/sony/mint/proprietary/etc/firmware/modem_fw.b21:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_fw.b21 \
    vendor/sony/mint/proprietary/etc/firmware/modem_fw.b22:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_fw.b22 \
    vendor/sony/mint/proprietary/etc/firmware/modem_fw.b23:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_fw.b23 \
    vendor/sony/mint/proprietary/etc/firmware/modem_fw.b25:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_fw.b25 \
    vendor/sony/mint/proprietary/etc/firmware/modem_fw.b26:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_fw.b26 \
    vendor/sony/mint/proprietary/etc/firmware/modem_fw.b29:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_fw.b29 \
    vendor/sony/mint/proprietary/etc/firmware/modem_fw.mdt:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem_fw.mdt
